module.exports = {
  apps: [
    {
      name: 'gitgenius-app',
      script: 'npm',
      args: 'run start -- -H 0.0.0.0 -p 6331',
      cwd: '/home/thehackitect/Desktop/PROJECTS/gitgenius',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 6331,
      },
      error_file: './logs/app-error.log',
      out_file: './logs/app-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
    },
    {
      name: 'gitgenius-worker',
      script: 'npm',
      args: 'run worker',
      cwd: '/home/thehackitect/Desktop/PROJECTS/gitgenius',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      cron_restart: '0 0 * * *',
    },
  ],
};
